### ISSUE TITLE
更新 docker-ce 同步方式

### ISSUE THREAD

**Issue by taoky** [ustclug/discussions#434]
### 问题描述 / Bug description

(To resolve https://github.com/tuna/issues/issues/1819#issuecomment-1717249270)

**Comment by taoky** [comment]
准备试一下，如果只对 */static/ 目录下面采取 fast skip 的策略，同步速度是否能够接受。

**Comment by taoky** [comment]
目前的配置：

```yaml
envs:
  UPSTREAM: https://download.docker.com/
  $UPSTREAM: https://download.docker.com/
  TSUMUGU_TIMEZONEFILE: https://download.docker.com/linux/centos/docker-ce-staging.repo
  TSUMUGU_PARSER: docker
  TSUMUGU_EXTRA: --head-before-get --skip-if-exists static/ --skip-if-exists 0.0.0 --skip-if-exists 2019 --skip-if-exists 2018 --skip-if-exists (nightly|edge|s390x|ppc64le|ppc64el|test|debug-.+)/.+\.(rpm|deb)
  TSUMUGU_EXCLUDE: --exclude debian/ --include debian/dists/${DEBIAN_CURRENT} --exclude fedora/ --include fedora/${FEDORA_CURRENT} --exclude ubuntu/ --include ubuntu/dists/${UBUNTU_LTS} --include ubuntu/dists/${UBUNTU_NONLTS}
image: ustcmirror/tsumugu:latest
```

```
2023-09-13T13:09:54.765473Z  INFO ThreadId(01) tsumugu::cli::sync: (Estimated) Total objects: 31286, total size: 499.42 GiB
```

通过过滤了大量已经 EOL 的发行版相关文件，以及对不常用的文件采取 fast skip 的策略，可以做到同步一次（不下载新文件）3 分钟。Debian 12 下测试 apt 正常。

**Comment by taoky** [comment]
Update:

```yaml
envs:
  UPSTREAM: https://download.docker.com/
  $UPSTREAM: https://download.docker.com/
  TSUMUGU_PARSER: docker
  TSUMUGU_EXTRA: --timezone 0 --head-before-get --skip-if-exists static/ --skip-if-exists 0.0.0 --skip-if-exists 2019 --skip-if-exists 2018 --skip-if-exists (nightly|edge|s390x|ppc64le|ppc64el|test|debug-.+)/.+\.(rpm|deb) --compare-size-only \.(rpm|deb)$
  TSUMUGU_EXCLUDE: --exclude debian/ --include debian/dists/${DEBIAN_CURRENT} --exclude fedora/ --include fedora/${FEDORA_CURRENT} --exclude ubuntu/ --include ubuntu/dists/${UBUNTU_LTS} --include ubuntu/dists/${UBUNTU_NONLTS}
```
