### ISSUE TITLE
stackage/7z中的文件未同步

### ISSUE THREAD

**Issue by ghommyl** [ustclug/discussions#485]
### 问题描述 / Bug description

stack在下载7z.dll时，有如下报错
```
> stack build
...
Preparing to download 7z.dll ...
Download expectation failure: ContentLength header
Expected: 1814016
Actual:   447488
For: https://mirrors.ustc.edu.cn/stackage/7z/7z.dll
```
问题原因是这个文件与stack-setup.yaml中的不匹配
```yaml
...
sevenzdll-info:
  content-length: 1814016
  sha256: 73578f14d50f747efa82527a503f1ad542f9db170e2901eddb54d6bce93fc00e
  url: https://mirrors.ustc.edu.cn/stackage/7z/7z.dll
sevenzexe-info:
  content-length: 545280
  sha256: 254cf6411d38903b2440819f7e0a847f0cfee7f8096cfad9e90fea62f42b0c23
  url: https://mirrors.ustc.edu.cn/stackage/7z/7z.exe
...
```
经过验证，镜像站中的7z.dll和7z.exe文件的长度和SHA256校验和均不匹配
在[setup-info的默认文件](https://raw.githubusercontent.com/commercialhaskell/stackage-content/master/stack/stack-setup-2.yaml)中，这两个文件指向https://github.com/commercialhaskell/stackage-content/releases/download/7z-22.01/7z.dll 和 https://github.com/commercialhaskell/stackage-content/releases/download/7z-22.01/7z.exe
可以更新镜像站中的文件，或者修改stack-setup.yaml中的content-length和sha256来解决这个问题
